MODEL:
  NUM_CLASSES: 45
  BACKBONE:
    OUT_CHANNELS: (512, 1024, 512, 256, 256, 256, 256)
  PRIORS:
    FEATURE_MAPS: [64, 32, 16, 8, 4, 2, 1]
    STRIDES: [8, 16, 32, 64, 128, 256, 512]
    MIN_SIZES: [20.48, 51.2, 133.12, 215.04, 296.96, 378.88, 460.8]
    MAX_SIZES: [51.2, 133.12, 215.04, 296.96, 378.88, 460.8, 542.72]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 6, 4, 4]
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 150000
  LR_STEPS: [100000, 120000]
  GAMMA: 0.1
  BATCH_SIZE: 4
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd512_coco_trainval35k'